---
# tasks file for cachepython
- name: Get the chip architecture
  command: uname -a
  register: chip_arch
  changed_when: chip_arch.stdout is not search("")
- name: Print message about not being able to run on 64 bit architecture
  debug:
    msg="The role can only run on 32 bit sustems. See README for more details"
  when: chip_arch.stdout is search("x86_64")
- name: Quit if the architecture is 64 bit
  meta: end_play
  when: chip_arch.stdout is search("x86_64")
- name: Copy the install script
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0744"
  loop:
    - { src: 'files/install.sh', dest: '/tmp/install.sh' }
- name: Unarchive the tar file
  unarchive:
    src: files/cache-perl.tar
    dest: /
- name: Make sure python-xml is installed to allow for yum and zypper to run through Ansible
  command: 'zypper install -y python-xml'
  when: ansible_distribution is search("SUSE")
  tags:
    - skip_ansible_lint # Need to install python-xml to get Ansible zypper/yum module to work - Chicken and egg!!
- name: Make sure python-xml is installed to allow for yum and zypper to run through Ansible
  command: 'yum install -y python-xml'
  when: ansible_distribution is not search("SUSE")
  tags:
    - skip_ansible_lint # Need to install python-xml to get Ansible zypper/yum module to work - Chicken and egg!!
- name: Make sure that make and gcc are installed
  zypper:
   name: "{{ item }}"
   state: "present"
  loop:
    - make
    - gcc
  when: ansible_distribution is search("SUSE")
- name: Make sure that make and gcc are installed
  yum:
   name: "{{ item }}"
   state: "present"
  loop:
    - make
    - gcc
  when: ansible_distribution is not search("SUSE")
- name: Run the install
  command: /tmp/install.sh 64
  when: chip_arch.stdout is search("x86_64")
- name: Run the install
  command: /tmp/install.sh 32
  when: chip_arch.stdout is not search("x86_64")
- name: copy Perl templates
  template:
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
     owner: root
     group: root
     mode: "{{ item.mode }}"
  loop:
     - { src: "templates/testauto.pl", dest: "/tmp/testauto.pl", mode: "0744" }
- name: Verify that the install is working as expected
  command: "/tmp/testauto.pl"
  environment:
    LD_LIBRARY_PATH: "/usr/local/cache-perl/bin"
  register: outpt
  changed_when: outpt.stdout is not search("")
- name: Print the verification output
  debug: msg="{{ outpt.stdout }}"
- name: Print whether the install has gone through or not
  debug: msg="INTERSYSTEMS CACHE PERL BINDING HAS BEEN INSTALLED SUCCESSFULLY"
  when: outpt.stdout is search("ok 1\nok 2\nok 3")
- name: Print whether the install has gone through or not
  fail: msg="INTERSYSTEMS CACHE PERL BINDING HAS NOT BEEN INSTALLED SUCCESSFULLY"
  when: outpt.stdout is not search("ok 1\nok 2\nok 3")
